#!/usr/bin/env ruby

require 'rubygems'
require 'poolparty'
require File.join(File.dirname(__FILE__), '..', 'clouds.rb')


dest_dir = "/tmp/#{pool.name}"

pool.clouds['app'].nodes.each do |node|
  $stdout.puts "Rsync-ing #{`pwd`.strip} to #{dest_dir}"
  command = "rsync -avz -e 'ssh -i #{ENV['HOME']}/.ec2/#{pool.name}.pem' --exclude='vendor/*' . #{node.user}@#{node.host}:#{dest_dir}"
  puts command
  `#{command}`
end
